apiVersion: v1
kind: Service
metadata:
  labels:
    safe.k8s.fmeflow.component: remoteengine
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: fmeflowremoteengineweb
spec:
  ports:
  - port: 8080
  selector:
    safe.k8s.fmeflow.component: remoteengine