apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeflow.component: remoteengine
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: fmeflow-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  {{- if and (not .Values.storage.useHostDir) .Values.storage.postgresql.class }}
  storageClassName: {{.Values.storage.postgresql.class}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.storage.postgresql.size}}
