apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fmeserver-migration-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.deployment.backupReadTimeout | quote }}
{{- include "fmeserver.ingress.annotations" . | indent 4 }}
spec:
  {{- include "fmeserver.ingress.tls" . }}
  rules:
    - http:
        paths:
          - backend:
              serviceName: fmeserverweb
              servicePort: 8080
            path: /fmerest/v3/migration/backup/download
      {{- if .Values.deployment.useHostnameIngress }}
      host: {{ .Values.deployment.hostname }}
      {{ end }}
