{{ if gt (int .Values.deployment.numCores) 1}}
apiVersion: {{ include "fmeserver.pdb.apiversion" . }}
kind: PodDisruptionBudget
metadata:
  name: core-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      safe.k8s.fmeserver.component: core
{{ end }}
