apiVersion: v1
kind: Service
metadata:
  labels:
    safe.k8s.fmeflow.component: core
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: engineregistration
spec:
  ports:
    - name: engineregistration
      port: 7070
  selector:
    safe.k8s.fmeflow.component: core