apiVersion: v1
kind: Service
metadata:
  labels:
    safe.k8s.fmeflow.component: websocket
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: fmeflowwebsocket
spec:
  ports:
  - name: websocket
    port: 7078
  clusterIP: None
  selector:
    safe.k8s.fmeflow.component: websocket
