apiVersion: {{ include "fmeflow.ingress.apiversion" . }}
kind: Ingress
metadata:
  name: fmeflow-migration-ingress
  annotations:
{{- if .Values.deployment.ingress.general.annotations }}
{{ toYaml .Values.deployment.ingress.general.annotations | indent 4 }}
{{ end }}
{{- if .Values.deployment.ingress.migration.annotations }}
{{ toYaml .Values.deployment.ingress.migration.annotations | indent 4 }}
{{ end }}
{{- include "fmeflow.ingress.annotations" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.deployment.ingress.general.ingressClassName }}
  {{- include "fmeflow.ingress.tls" . }}
  rules:
    - http:
        paths:
          - backend:
{{ include "fmeflow.ingress.web.service" . | indent 14 }}
            path: /fmerest/v3/migration/backup/download
            {{ include "fmeflow.ingress.pathType" . }}
          - backend:
{{ include "fmeflow.ingress.web.service" . | indent 14 }}
            path: /fmerest/v3/migration/restore/upload
            {{ include "fmeflow.ingress.pathType" . }}
      {{- if .Values.deployment.useHostnameIngress }}
      host: {{ .Values.deployment.hostname }}
      {{ end }}
