{{- if not .Values.fmeflow.database.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fmeflow.fullname" . }}
  labels:
    {{- include "fmeflow.common.labels" . | indent 4 }}
type: Opaque
data:
  fmeflow-db-password: {{ .Values.fmeflow.database.password | b64enc | quote }}
{{- end -}}
